controllers/Book.py
from app import dao as DAO, app
from copy import copy
from os.path import join
from uuid import uuid4

class Book:
    def __init__(self, bid=None):
        self.dao = copy(DAO)
        if bid:
            book_info = self.dao.book.get_by_bid(bid)
            if book_info:
                self.bid = book_info[0]
                self.uid = self.dao.request.get_owner(self.bid)
                self.title = book_info[1]
                self.author = book_info[2]
                self.publishyear = book_info[3]
                self.catalog = book_info[4]
                self.review = book_info[5]
                self.available = book_info[6]
                self.photos = self.get_photos(self.bid)

    def get_follower_id(self):
        uids = self.dao.follow.get_follower(self.bid)
        return uids

#    def get_follower(self):
#        uids = self.get_follower_id()
#        users = [ self.dao.user.get_by_id() for id in uids ]
#        return users

    def get_requester_id(self, available=1):
        uids = self.dao.request.get_requester_id(self.bid, available)
        return uids

    def get_requester(self):
        uids = self.get_requester_id()
        users = [ self.dao.user.get_by_id(uid) for uid in uids ]
        return users

    def update(self, new_photos=[]):
        self.dao.book.update(self)
        for photo in new_photos:
            self.dao.photo.add_photo(self.bid, photo)

    def add_book(self, uid):
        bid = self.dao.book.add_book(self)
        for photo in self.photos:
            self.dao.photo.add_photo(bid, photo)
        self.dao.request.add_book(uid, bid)
        return bid

    def save_photo(self, image):
        path = app.config['PHOTOS_SAVE_PATH']
        filename = uuid4().hex + '_raw.png'
        image.save(join(path, filename))
        return filename

    def get_photos(self, bid):
        return self.dao.photo.get_photos(bid)

    def delete_photo(self, photo):
        return self.dao.photo.delete_photo(photo)

    def set_cover(self, photo):
        return self.dao.photo.set_cover(self.bid, photo)

    def get_all_books(self):
        return self.dao.book.get_all_books()

    def search_by_author(self, author, limit):
        return self.dao.book.search_by_author(author=author, limit=limit)

    def search_by_year(self, year, limit):
        return self.dao.book.search_by_year(year=year, limit=limit)

    def search_by_catalog(self, catalog, limit):
        return self.dao.book.search_by_catalog(catalog=catalog, limit=limit)

    def search(self, text, limit):
        return self.dao.book.search(text=text, limit=limit)

    def decline_all(self):
        return self.dao.request.decline_all(self.bid)

    def get_accepted_uid(self):
        uid = self.dao.request.get_accepted_uid(self.bid)
        return uid

    def add_comment(self, uid, text):
        if text:
            self.dao.comment.add_comment(uid=uid, bid=self.bid, text=text)

    def get_comments(self):
        return self.dao.comment.get_comments(self.bid)

    def edit_comment(self, text, cid):
        return self.dao.comment.edit_comment(text, cid)

    def hide_comment(self, cid):
        return self.dao.comment.hide_comment(cid)

controllers/Notifications.py
from app import dao as DAO
from copy import copy
from flask import url_for

class Notifications:
    def __init__(self):
        self.dao = copy(DAO)

    
    def seen(self, nid):
        self.dao.notification.seen_notif(nid)

# thong bao da dong y
    def accept_notif(self, user, book):
        text = 'Bạn đã được đồng ý lấy quyển <a href="{}">{}<a> hãy xác nhận đồng ý và chủ sở hữu sẽ chuyển sách cho bạn. Lưu ý yêu cầu lấy\
        sẽ được tự động xác nhận trong 1 ngày tính từ khi bạn nhận được thông báo này'\
        .format(url_for('book_routes.book', bid=book.bid), book.title)
        return self.dao.notification.make_notif(user.id, text)

# thong bao da tu choi
    def decline_notif(self, user, book):
        text = 'Bạn đã không được đồng ý lấy quyển <a href="{}">{}<a>. Điểm sẽ được cộng lại cho bạn'\
        .format(url_for('book_routes.book', bid=book.bid), book.title)
        return self.dao.notification.make_notif(user.id, text)

# thong bao da xac nhan
    def confirm_notif(self, user, book):
        text = '<a href="">{}</a> đã xác nhận lấy quyển <a href="{}">{}</a>, hãy bắt đầu gửi sách cho họ'\
        .format(user.name, url_for('book_routes.book', bid=book.bid), book.title)
        return self.dao.notification.make_notif(book.uid, text)

# thong bao khong xac nhan
    def unconfirm_notif(self, user, book):
        text = '<a href="">{}</a> đã không xác nhận lấy quyển <a href="{}">{}</a>, hãy xem xét các yêu cầu lấy còn lại'\
            .format(user.name, url_for('book_routes.book', bid=book.bid), book.title)
        return self.dao.notification.make_notif(book.uid, text)

# thong bao sach da go
    def removed_notif(self, user, book):
        text = 'Quyển <a href="{}">{}</a> mà bạn yêu cầu đã bị gỡ, điểm đã được cộng lại cho bạn'\
            .format(url_for('book_routes.book', bid=book.bid), book.title)
        return self.dao.notification.make_notif(user.id, text)

# thong bao sa cho nguoi khac lay
    def taken_notif(self, user, book):
        text = 'Quyển <a href="{}">{}</a> mà bạn yêu cầu đã cho người khác lấy, điểm đã được cộng lại cho bạn'\
            .format(url_for('book_routes.book', bid=book.bid), book.title)
        return self.dao.notification.make_notif(user.id, text)

# thong bao sach ban muon da co the yeu cau lay
    def available_notif(self, user, book):
        text = 'Quyển <a href="{}">{}</a> mà bạn theo dõi đã được đăng. Bây giờ, bạn có thể yêu cầu lấy'\
            .format(url_for('book_routes.book', bid=book.bid), book.title)
        return self.dao.notification.make_notif(user.id, text)

# thong bao co nguoi yeu cau muon
    def requested_notif(self, user, book):
        text = '<a href="">{}</a> đã yêu cầu lấy quyển <a href="{}">{}</a>'\
            .format(user.name, url_for('book_routes.book', bid=book.bid), book.title)
        return self.dao.notification.make_notif(book.uid, text)

    def tagged_notif(self, user, book):
        text = 'Bạn đã được nhắc đến trong một <a href="{}">bình luận</a>'\
            .format(url_for('book_routes.book', bid=book.bid))
        return self.dao.notification.make_notif(user.id, text)

routes/book_view.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify
from werkzeug.urls import url_parse
from flask_login import current_user, login_required
from flask_socketio import send, emit
from app import dao, socket
from controllers.Book import Book
from controllers.Paging import Paging
from controllers.Notifications import Notifications
from controllers.Forms import *
from copy import copy
import json
import datetime

book_view = Blueprint('book_routes', __name__, template_folder='/templates')

@socket.on('message')
def handleMessage(msg):
    msg['time'] = str(datetime.datetime.now())
    send(msg, broadcast=True)

@socket.on('typing')
def handleTyping(msg):
	emit('typing', msg, broadcast=True)

@book_view.route('/')
@book_view.route('/home')
def home():
    page =  request.args.get('page', 1, type=int)
    book = Book()
    all_books = book.get_all_books()
    books = Paging(list=all_books, len_each_page=9, page=page)
    this_url = url_for('book_routes.home') + '?'

    return render_template('home.html', books=books, bookDAO=book, this_url=this_url)

@book_view.route('/new_book', methods=['GET', 'POST'])
@login_required
def new_book():
    form = BookForm()
    if form.validate_on_submit():
        book = Book()
        book.title = form.title.data
        book.author = form.author.data
        book.publishyear = str(form.publishyear.data)
        book.catalog = form.catalog.data
        book.review = form.review.data
        book.photos = []
        
        images = form.image.data
        for image in images:
            filename = book.save_photo(image)
            book.photos.append(filename)

        bid = book.add_book(current_user.id)
        current_user.update(inc_point=1)
        flash('Thêm sách mới thành công')
        return redirect(url_for('book_routes.book', bid=bid))

    return render_template('new_book.html', form=form)

@book_view.route('/book/<int:bid>/edit', methods=['GET', 'POST'])
@login_required
def edit_book(bid):
    form = BookForm()
    book = Book(bid)
    if request.method == 'GET':
        form.title.data = book.title
        form.author.data = book.author
        form.publishyear.data = book.publishyear
        form.catalog.data = book.catalog
        form.review.data = book.review

    elif form.validate_on_submit():
        book.title = form.title.data
        book.author = form.author.data
        book.publishyear = str(form.publishyear.data)
        book.catalog = form.catalog.data
        book.review = form.review.data
        
        new_photos = []
        images = form.image.data
        for image in images:
            filename = book.save_photo(image)
            new_photos.append(filename)

        book.update(new_photos)
        flash('Sửa thông tin sách thành công')
        return redirect(url_for('book_routes.book', bid=book.bid))

    return render_template('edit_book.html', form=form)

@book_view.route('/book/<int:bid>', methods=['GET','POST'])
def book(bid):
    book = Book(bid)
    if request.method == 'POST':
        text = request.form.get('text').replace('<div><br></div>','').replace('&nbsp;', ' ')
        uid = request.form.get('uid')
        book.add_comment(text=text,uid=uid)

        return jsonify(None)
    else:
        Owner = User(book.uid)

        return render_template('book_view.html', book=book, Owner=Owner, dao=copy(dao))

@book_view.route('/get_comment/<int:bid>', methods=['POST'])
def get_comments(bid):
    book = Book(bid)
    result = []
    for cmt in book.get_comments():
        user = dao.user.get_by_id(cmt[1])
        avatar = user[6]
        name = user[1]
        time = str(cmt[5])
        text = cmt[3]
        result.append({'avatar':avatar, 'name':name, 'time':time, 'text':text})

    return jsonify(result)

@book_view.route('/book/<int:bid>/set_cover/<photo>')
@login_required
def set_cover(bid, photo):
    book = Book(bid)
    if book.uid == current_user.id and photo in book.photos:
        book.set_cover(photo)

    return redirect(url_for('book_routes.book', bid=bid))

@book_view.route('/book/<int:bid>/delete_photo/<photo>')
@login_required
def delete_photo(bid, photo):
    book = Book(bid)
    if book.uid == current_user.id and photo in book.photos:
        book.delete_photo(photo)

    return redirect(url_for('book_routes.book', bid=bid))

@book_view.route('/book/<int:bid>/remove_book')
@login_required
def remove_book(bid):
    book = Book(bid)
    if book.uid == current_user.id:
        book.available=0
        book.update()
        current_user.update(inc_point=-1)
        uids = book.get_requester_id(available=1)
        book.decline_all()
        notif = Notifications()
        for uid in uids:
            user = User(uid)
            user.update(inc_point=1)
            notif.removed_notif(user, book)

    next_page = request.args.get('next')
    if not next_page or url_parse(next_page).netloc != '':
        next_page = url_for('user_routes.my_book')
        return redirect(next_page)

    return redirect(url_for('book_routes.book', bid=bid))

@book_view.route('/book/<int:bid>/post_book')
@login_required
def post_book(bid):
    book = Book(bid)
    if book.uid == current_user.id:
        book.available=1
        book.update()
        current_user.update(inc_point=1)

        uids = book.get_follower_id()

        notif = Notifications()
        for uid in uids:
            notif.available_notif(User(uid), book)

    next_page = request.args.get('next')
    if not next_page or url_parse(next_page).netloc != '':
        next_page = url_for('user_routes.my_book')
        return redirect(next_page)

    return redirect(url_for('book_routes.book', bid=bid))

@book_view.route('/request/<int:bid>')
@login_required
def request_book(bid):
    book = Book(bid=bid)
    if current_user.id not in book.get_requester_id():
        if current_user.request(bid):
            Notifications().requested_notif(current_user, book)
            flash('Đã yêu cầu')
        else: flash('Có lỗi xảy ra hoặc không đủ điểm')
    return redirect(url_for('book_routes.book', bid=bid))

@book_view.route('/cancel_request/<int:bid>')
@login_required
def cancel_request(bid):
    if current_user.cancel_request(bid):
        flash('Đã hủy yêu cầu')
    return redirect(url_for('book_routes.book', bid=bid))

@book_view.route('/follow/<int:bid>')
@login_required
def follow(bid):
    current_user.follow(bid)
    flash('Đã theo dõi')
    return redirect(url_for('book_routes.book', bid=bid))

@book_view.route('/unfollow/<int:bid>')
@login_required
def unfollow(bid):
    current_user.unfollow(bid)
    flash('Đã bỏ theo dõi')
    return redirect(url_for('book_routes.book', bid=bid))

# search

@book_view.route('/home/search/author/<author>')
def search_by_author(author):
    page =  request.args.get('page', 1, type=int)
    book = Book()
    raw_books = book.search_by_author(author=author, limit=1000)
    books = Paging(list=raw_books, len_each_page=9, page=page)
    this_url = url_for('book_routes.search_by_author', author=author) + '?'

    return render_template('home.html', books=books, bookDAO=book, this_url=this_url)

@book_view.route('/home/search/year/<year>')
def search_by_year(year):
    page =  request.args.get('page', 1, type=int)
    book = Book()
    raw_books = book.search_by_year(year=year, limit=1000)
    books = Paging(list=raw_books, len_each_page=9, page=page)
    this_url = url_for('book_routes.search_by_year', year=year) + '?'

    return render_template('home.html', books=books, bookDAO=book, this_url=this_url)

@book_view.route('/home/search/catalog/<catalog>')
def search_by_catalog(catalog):
    page =  request.args.get('page', 1, type=int)
    book = Book()
    raw_books = book.search_by_catalog(catalog=catalog, limit=1000)
    books = Paging(list=raw_books, len_each_page=9, page=page)
    this_url = url_for('book_routes.search_by_catalog', catalog=catalog) + '?'

    return render_template('home.html', books=books, bookDAO=book, this_url=this_url)

@book_view.route("/livesearch", methods=["POST"])
def live_search():
    text = request.form.get("text")
    book = Book()
    result = book.search(text=text, limit=7)
    if len(result)<7:
        books = book.search_by_author(author=text, limit=7-len(result))
        temp = []
        for x in books:
            title = '<b>Tác giả ' + x[2] + ': </b>' + x[1]
            temp += [(x[0], title)]
        result += temp
    if len(result)<7:
        books = book.search_by_year(year=text, limit=7-len(result))
        temp = []
        for x in books:
            title = '<b>Năm ' + str(x[3]) + ': </b>' + x[1]
            temp += [(x[0], title)]
        result += temp

    return jsonify(result)

@book_view.route('/home/search')
def search():
    text =  request.args.get('text', None, type=str)
    page =  request.args.get('page', 1, type=int)
    book = Book()
    raw1_books = book.search(text=text, limit=1000)
    raw2_books = book.search_by_author(author=text, limit=1000)
    raw3_books = book.search_by_year(year=text, limit=1000)
    books = Paging(list=raw1_books+raw2_books+raw3_books, len_each_page=9, page=page)
    this_url = url_for('book_routes.search', text=text) + '&'

    return render_template('home.html', books=books, bookDAO=book, this_url=this_url)

templates/base_user_view.html
{% extends "layout.html" %}

{% block content %}
    
    <div class="row justify-content-center">
        <div class="col-md-3" id='left_main'>
            <div class='row mini_profile'>
                <div class="col-sm-4" id='mini_avatar'>
                    <a href=""><img src="{{current_user.get_avatar_url()}}"></a>
                </div>
                <div class="col-sm-8 justify-content-center" id='mini_info'>
                    <div id='name'>{{current_user.name}}</div>
                    <div><a href="{{url_for('user_routes.edit_profile')}}" id='edit'><i class="fas fa-pencil-alt"></i> Sửa Hồ Sơ</a></div>
                </div>
            </div>
            <div id='left_menu'>
                <ul>
                    <li {% block profile %}{% endblock %}><a href="{{url_for('user_routes.edit_profile')}}"><i class="fas fa-user"></i><span>Tài khoản của tôi</span></a></li>
                    <li {% block notification %}{% endblock %}><a href="{{url_for('user_routes.notification')}}"><i class="fas fa-bell"></i><span>Thông báo</span></a></li>
                    <li {% block my_book %}{% endblock %}><a href="{{url_for('user_routes.my_book')}}"><i class="fas fa-book"></i><span>Sách của tôi</span></a></li>
                    <li {% block following %}{% endblock %}><a href="{{url_for('user_routes.following')}}"><i class="fas fa-folder-plus"></i><span>Đang theo dõi</span></a></li>
                    <li {% block requesting %}{% endblock %}><a href="{{url_for('user_routes.requesting')}}"><i class="fas fa-cart-plus"></i><span>Đang yêu cầu</span></a></li>
                </ul>
            </div>
        </div>

        <div class="col-md-9" id='right_main'>
            <div class="account-head">{% block right_main_head %}{% endblock %}</div>
            {% block right_main %}{% endblock %}
        </div>
    </div>

{% endblock %}

templates/crop_avatar.html
<head>
    <meta charset="UTF-8">
    <title>Cắt ảnh</title>
    {{ avatars.jcrop_css() }}
    <style>
    </style>
</head>
<body>
    <h1>Cắt ảnh</h1>
    <div style="float:left">{{ avatars.crop_box('get_avatar', current_user.avatar) }}</div>
    <div style="float:left">{{ avatars.preview_box('get_avatar', current_user.avatar) }}</div>
    <form method="post">
        <input type="hidden" id="x" name="x">
        <input type="hidden" id="y" name="y">
        <input type="hidden" id="w" name="w">
        <input type="hidden" id="h" name="h">
        <input type="submit" value="Xong">
    </form>
    {{ avatars.jcrop_js() }}
    {{ avatars.init_jcrop() }}
</body>

templates/following_book.html
{% extends "base_user_view.html" %}

{% block following %} class="is-active" {% endblock %}

{% block right_main_head %}Sách đang theo dõi{% endblock %}

{% block right_main %}
<div class="row info_page">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-4">
                <p>Sách đang theo dõi: {{len}}</p>
            </div>
            <div class="col-md-6"></div>
            <div class="col-md-2"></div>
        </div>
    </div>
    {% for book in books.page %}
    <div class="col-md-12 boder_book_view">
        <div class="row" id="book_owner_view">
            <div class="col-md-2">
                <a href="{{url_for('book_routes.book', bid=book.bid)}}">
                    {% if book.photos %}
                    <img src="{{ url_for('static',filename='/image/book_photos/') + book.photos[0] }}" />
                    {% else %}
                    <img src="{{url_for('static',filename='/image/no_image.jpg')}}" />
                    {% endif %}
                </a>
            </div>
            <div class="col-md-4">
                <a href="{{url_for('book_routes.book', bid=book.bid)}}">{{book.title}}</a>{% if not book.available %}<span> (Đã gỡ xuống)</span>{%endif%}<br /><br />
                <a href="{{url_for('book_routes.search_by_author', author=book.author)}}">{{book.author}}</a><br /><br />
                <a href="{{url_for('book_routes.search_by_year', year=book.publishyear)}}">{{book.publishyear}}</a><br /><br />
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-2" style="text-align:center;">
                <a href="{{url_for('book_routes.unfollow', bid=book.bid)}}"><button class="btn btn-primary" style="font-size:16px">Bỏ theo dõi</button></a>
            </div>
        </div>
    </div>
    {% endfor %}

    {% if books.size %}
    <div>
        <ul id="page_nav">
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=1)}}"><div> << </div></a></li>
            {% if books.pos > 1 %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.pos-1)}}"><div> <  </div></a></li>
            {% if books.pos > 3 %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.pos-3)}}"><div>{{books.pos-3}}</div></a></li>
            {% endif %}
            {% if books.pos > 2 %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.pos-2)}}"><div>{{books.pos-2}}</div></a></li>
            {% endif %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.pos-1)}}"><div>{{books.pos-1}}</div></a></li>
            {% endif %}

            <li><a class="page_btn active" href="{{url_for('user_routes.following', page=books.pos)}}"><div>{{books.pos}}</div></a></li>

            {% if books.pos < books.size %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.pos+1)}}"><div>{{books.pos+1}}</div></a></li>
            {% if books.pos+1 < books.size %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.pos+2)}}"><div>{{books.pos+2}}</div></a></li>
            {% endif %}
            {% if books.pos+2 < books.size %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.pos+3)}}"><div>{{books.pos+3}}</div></a></li>
            {% endif %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.pos+1)}}"><div> >  </div></a></li>
            {% endif %}
            <li><a class="page_btn" href="{{url_for('user_routes.following', page=books.size)}}"><div> >> </div></a></li>
        </ul>
    </div>
    {% endif %}

</div>

{% endblock %}

templates/login.html
{% extends "layout.html" %}

{% block content %}

    <div class="row align-items-center justify-content-center main_background">
        <div class="col-lg-5 form">
            <div class="form_head">
                <h4>Đăng nhập</h4>
                <p>Nhập email và mật khẩu tài khoản Boook</p>
            </div>
            <form action="" method="post">
                {{ form.hidden_tag() }}
                <div class="input">
                    {{ form.email(placeholder="acb@email.com") }}
                    {% for error in form.email.errors %}
                    <p style="color: red;">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="input">
                    {{ form.password(placeholder="Mật khẩu") }}
                    {% for error in form.password.errors %}
                    <p style="color: red;">{{ error }}</p>
                    {% endfor %}
                </div>
                <div>{{ form.remember_me() }} {{ form.remember_me.label }}</div>
                {{ form.submit() }}
            </form>
            <p class="forgot-pass"><a href="{{ url_for('user_routes.reset_password_request') }}">Quên mật khẩu?</a></p>
            <p class="create-account">Chưa có tài khoản? <a href="{{ url_for('user_routes.register') }}">Tạo tài khoản!</a></p>
        </div>
    </div>

{% endblock %}

templates/my_book.html
{% extends "base_user_view.html" %}

{% block my_book %} class="is-active" {% endblock %}

{% block right_main_head %}Quản lý sách{% endblock %}

{% block right_main %}
<div class="row info_page">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-4">
                <p>Sách hiện có: {{len}}</p>
            </div>
            <div class="col-md-6"></div>
            <div class="col-md-2">
                <a href="/new_book"><button id="new_book">Thêm sách mới</button></a>
            </div>
        </div>
    </div>
    {% for book in books.page %}
    <div class="col-md-12 boder_book_view">
        <div class="row" id="book_owner_view">
            <div class="col-md-2">
                <a href="{{url_for('book_routes.book', bid=book.bid)}}">
                    {% if book.photos %}
                    <img src="{{ url_for('static',filename='/image/book_photos/') + book.photos[0] }}" />
                    {% else %}
                    <img src="{{url_for('static',filename='/image/no_image.jpg')}}" />
                    {% endif %}
                </a>
            </div>
            <div class="col-md-4">
                <a href="{{url_for('book_routes.book', bid=book.bid)}}">{{book.title}}</a>{% if not book.available %}<span> (Đã gỡ xuống)</span>{%endif%}<br /><br />
                <a href="{{url_for('book_routes.search_by_author', author=book.author)}}">{{book.author}}</a><br /><br />
                <a href="{{url_for('book_routes.search_by_year', year=book.publishyear)}}">{{book.publishyear}}</a><br /><br />
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-2">
                {% if not book.get_accepted_uid()%}
                {% if book.available %}
                <a href="{{url_for('book_routes.remove_book', bid=book.bid)}}"><button id="remove_book">Gỡ sách</button></a>
                {% else %}
                <a href="{{url_for('book_routes.post_book', bid=book.bid)}}"><button id="post_book">Đăng sách</button></a>
                {% endif %}
                {% endif %}
            </div>
        </div>

        {% with geter = book.dao.user.get_by_id(book.get_accepted_uid()) %}
        {% if geter %}
        <div class="col-md-12">
            <p style="color:red;
                        font-size:16px;
                        text-align:center;">
                Đã đồng ý cho <a href="" style="color:blue;">{{geter[1]}}</a> lấy, chờ xác nhận
            </p>
        </div>

        {% else %}

        {% with users = book.get_requester() %}
        {% if users %}
        <div class="col-md-12">
            Yêu cầu lấy sách này:
        </div>
        <div class="col-md-12 requesters_box">
            {% for user in users %}
            <div class="row requester">
                <div class="col-md-4"><a href="{{url_for('user_routes.user', uid=user[0])}}">{{user[1]}}</a></div>
                <div class="col-md-2">Hà Nội</div>
                <div class="col-md-2">Điểm: {{user[8]}}</div>
                <div class="col-md-2">
                    <a href="{{url_for('user_routes.accept', uid=user[0], bid=book.bid)}}"><button id="">Đồng ý</button></a>
                </div>
                <div class="col-md-2">
                    <a href="{{url_for('user_routes.decline', uid=user[0], bid=book.bid)}}"><button id="">Từ chối</button></a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}

        {% endif %}
        {% endwith %}
    </div>
    {% endfor %}

    <div>
        <ul id="page_nav">
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page=1"><div> << </div></a></li>
            {% if books.pos > 1 %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.pos-1}}"><div> <  </div></a></li>
            {% if books.pos > 3 %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.pos-3}}"><div>{{books.pos-3}}</div></a></li>
            {% endif %}
            {% if books.pos > 2 %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.pos-2}}"><div>{{books.pos-2}}</div></a></li>
            {% endif %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.pos-1}}"><div>{{books.pos-1}}</div></a></li>
            {% endif %}

            <li><a class="page_btn active" href="{{url_for('user_routes.my_book')}}?page={{books.pos}}"><div>{{books.pos}}</div></a></li>

            {% if books.pos < books.size %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.pos+1}}"><div>{{books.pos+1}}</div></a></li>
            {% if books.pos+1 < books.size %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.pos+2}}"><div>{{books.pos+2}}</div></a></li>
            {% endif %}
            {% if books.pos+2 < books.size %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.pos+3}}"><div>{{books.pos+3}}</div></a></li>
            {% endif %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.pos+1}}"><div> >  </div></a></li>
            {% endif %}
            <li><a class="page_btn" href="{{url_for('user_routes.my_book')}}?page={{books.size}}"><div> >> </div></a></li>
        </ul>
    </div>

</div>

{% endblock %}